package prus.justweatherapp.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006496)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCCE5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E31)
val md_theme_light_secondary = Color(0xFF50606F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD4E4F6)
val md_theme_light_onSecondaryContainer = Color(0xFF0D1D2A)
val md_theme_light_tertiary = Color(0xFF285EA7)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD6E3FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001B3D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF001849)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF001849)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72787E)
val md_theme_light_inverseOnSurface = Color(0xFFEEF0FF)
val md_theme_light_inverseSurface = Color(0xFF002B75)
val md_theme_light_inversePrimary = Color(0xFF91CDFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006496)
val md_theme_light_outlineVariant = Color(0xFFC2C7CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF91CDFF)
val md_theme_dark_onPrimary = Color(0xFF003350)
val md_theme_dark_primaryContainer = Color(0xFF004B72)
val md_theme_dark_onPrimaryContainer = Color(0xFFCCE5FF)
val md_theme_dark_secondary = Color(0xFFB8C8D9)
val md_theme_dark_onSecondary = Color(0xFF23323F)
val md_theme_dark_secondaryContainer = Color(0xFF394856)
val md_theme_dark_onSecondaryContainer = Color(0xFFD4E4F6)
val md_theme_dark_tertiary = Color(0xFFA9C7FF)
val md_theme_dark_onTertiary = Color(0xFF003063)
val md_theme_dark_tertiaryContainer = Color(0xFF00468C)
val md_theme_dark_onTertiaryContainer = Color(0xFFD6E3FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001849)
val md_theme_dark_onBackground = Color(0xFFDBE1FF)
val md_theme_dark_surface = Color(0xFF001849)
val md_theme_dark_onSurface = Color(0xFFDBE1FF)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CE)
val md_theme_dark_outline = Color(0xFF8C9198)
val md_theme_dark_inverseOnSurface = Color(0xFF001849)
val md_theme_dark_inverseSurface = Color(0xFFDBE1FF)
val md_theme_dark_inversePrimary = Color(0xFF006496)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF91CDFF)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF6490B5)
val accent = Color(0xFFF9BA01)
val purple = Color(0xFFA185EE)
val light_accent = Color(0xFF795900)
val light_onaccent = Color(0xFFFFFFFF)
val light_accentContainer = Color(0xFFFFDEA0)
val light_onaccentContainer = Color(0xFF261900)
val dark_accent = Color(0xFFFCBC07)
val dark_onaccent = Color(0xFF402D00)
val dark_accentContainer = Color(0xFF5C4300)
val dark_onaccentContainer = Color(0xFFFFDEA0)


val green = Color(0xFF97D700)
val yellow = Color(0xFFFCE300)
val orange = Color(0xFFFF8200)
val red = Color(0xFFEF3340)
val violet = Color(0xFF9063CD)

